version: "3.8"

services:
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env.dev

  blog-prod:
    image: "production-container-blog"
    build:
      context: ./api
      cache_from:
        - "production-container-blog"
    command: gunicorn myblog.myblog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  front-prod:
    image: "production-container-blog"
    build:
      context: ./frontend
      cache_from:
        - "production-container-blog"
    ports:
      - 3000:3000
    volumes:
      - front_build:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf:ro
      - front_build:/var/www/front
    container_name: "web-server"
    depends_on:
      - blog-prod
      - front-prod

volumes:
  front_build:
  postgres_data:
