version: "3.8"

services:
  api:
    image: "production-backend-container"
    container_name: api
    build:
      context: ./api
      cache_from:
        - "production-backend-container"
    command: sh -c "cd myblog/ && gunicorn myblog.wsgi:application --reload --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/usr/src/blog/

  frontend:
    image: "production-frontend-container"
    container_name: frontend
    build:
      context: ./frontend
      cache_from:
        - "production-frontend-container"
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/usr/src/frontend/

  nginx:
    image: "web-server"
    container_name: nginx
    build: ./nginx
    ports:
      - 80:8080
    depends_on:
      - api
      - frontend
