version: "3.8"

services:
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env.dev

  blog-dev:
    image: "blog:dev"
    build:
      target: development_build
      context: ./api
      cache_from:
        - "blog:dev"
      args:
        DJANGO_ENV: development
    command: python -Wd myblog/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./api/.env.dev
    depends_on:
      - db

  front-dev:
    image: "front:dev"
    build:
      target: development_front
      context: ./frontend
    command: npm -Wd start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/front
      - /front/node_modules

volumes:
  postgres_data:
