version: "3.8"

services:
  api:
    image: "production-backend-container"
    container_name: api
    build:
      context: ./api
      cache_from:
        - "production-backend-container"
    command: sh -c "cd myblog/ && gunicorn myblog.wsgi:application --reload --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    volumes:
      - django_static:/usr/src/blog/myblog/static
      - django_media:/usr/src/blog/myblog/media

  frontend:
    image: "production-frontend-container"
    container_name: frontend
    build:
      context: ./frontend
      cache_from:
        - "production-frontend-container"
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/usr/src/frontend/
      - front_build:/usr/src/frontend/build/

  nginx:
    image: "web-server"
    container_name: nginx
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - django_static:/usr/src/back/static
      - django_media:/usr/src/back/media
      - front_build:/usr/share/nginx/html
    depends_on:
      - api

volumes:
  django_static:
  django_media:
  front_build:
