version: "3.8"

services:
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  blog:
    image: "blog:dev"
    build:
      target: development_build
      context: ./myblog
      cache_from:
        - "blog:dev"
      args:
        DJANGO_ENV: development
    command: python -Wd myblog/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
