version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - poetry run mypy myblog/ # --ignore-missing-imports
      - poetry run black myblog/
      - poetry run flake8 myblog/ --show-source --statistics --count
      - export PYTHONPATH=${PYTHONPATH}:${PWD}
      - poetry run pylint 
        --load-plugins pylint_django
        --django-settings-module=myblog.settings
        --ignore-patterns=Dockerfile
        ./myblog/*
      - npm run --prefix ./frontend format
      - npm run --prefix ./frontend lint

  docker-build:
      desc: Builds docker image/containers/volumes and prompt django superuser
      cmds:
        - docker compose up --build -d
        - docker ps

  docker-up:
      desc: start and build containers, etc... (existing volumes)
      cmds:
        - docker compose up -d
        - docker ps

  docker-down:
      desc: stop and remove containers, etc... (persist volumes)
      cmds:
        - docker compose down
        - docker ps

  docker-start:
      desc: start containers
      cmds:
        - docker compose start
        - docker ps

  docker-stop:
      desc: stop containers
      cmds:
        - docker compose stop
        - docker ps

