version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - poetry run mypy myblog/ # --ignore-missing-imports
      - poetry run black myblog/
      - poetry run flake8 myblog/ --show-source --statistics --count
      - export PYTHONPATH=${PYTHONPATH}:${PWD}
      - poetry run pylint 
        --load-plugins pylint_django
        --django-settings-module=myblog.settings
        ./myblog/*

        

  test:
    desc: Runs test on code
    cmds: 
      - >
        poetry run pytest
        --cov=gh_star_count
        --cov-report=html

  build:
      desc: Builds the python package
      cmds:
        - poetry build

  docs-serve:
    desc: Serve the documentation locally
    deps:
      - test
      - generate-changelog
    cmds:
      - poetry run mkdocs serve

  docs-publish:
    desc: Publish the documentation to gh-pages
    deps:
      - generate-changelog
    cmds:
      - poetry run gh-deploy --force

  generate-changelog:
    desc: Generates the changelog
    cmds:
      - poetry run git-changelog --output CHANGELOG.md .
