# Generated by Django 4.1.4 on 2022-12-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="Titre"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technologie", "Tech"),
                            ("société", "Society"),
                            ("lectures", "Lect"),
                            ("divers(tissement)", "Entertainment"),
                            ("opinion", "Opinion"),
                        ],
                        default="opinion",
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="photos/%Y/%m/%d")),
                ("excerpt", models.CharField(max_length=150)),
                ("month", models.CharField(max_length=4)),
                ("day", models.CharField(max_length=2)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Publier"),
                ),
                ("content", models.TextField(verbose_name="Corps")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "ordering": ["-date_created"],
            },
        ),
    ]
