version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and reports on issues.
    cmds:
      - poetry run mypy myblog/ # --ignore-missing-imports
      - poetry run black myblog/
      - poetry run flake8 myblog/ --show-source --statistics --count
      - export PYTHONPATH=${PYTHONPATH}:${PWD}
      - poetry run pylint 
        --load-plugins pylint_django
        --django-settings-module=myblog.settings
        --ignore-patterns=Dockerfile
        ./myblog/*

  docker-dev-build:
      desc: Builds docker image/containers/volumes for development
      cmds:
        - docker compose -f docker-compose-dev.yml up --build -d
        - docker ps

  docker-dev-down:
      desc: stop and remove containers for development
      cmds:
        - docker compose -f docker-compose-dev.yml down
        - docker ps

  docker-prod-build:
      desc: Builds docker image/containers/volumes in production
      cmds:
        - docker compose -f docker-compose-prod.yml up --build
        - docker ps

  docker-prod-down:
      desc: stop and remove containers in production
      cmds:
        - docker compose -f docker-compose-prod.yml down
        - docker ps


