name: Deployer le blog
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: "eu-west-3"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push Docker Images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: blog
          IMAGE_TAG: prod
        run: |
          docker-compose build

          docker tag blog:latest 225275344647.dkr.ecr.eu-west-3.amazonaws.com/blog:latest
          docker-compose push 225275344647.dkr.ecr.eu-west-3.amazonaws.com/blog:latest

          docker tag front:latest 225275344647.dkr.ecr.eu-west-3.amazonaws.com/front:latest
          docker-compose push 225275344647.dkr.ecr.eu-west-3.amazonaws.com/front:latest

          docker tag postgres:12.0-alpine 225275344647.dkr.ecr.eu-west-3.amazonaws.com/db:latest
          docker-compose push 225275344647.dkr.ecr.eu-west-3.amazonaws.com/db:latest

      - name: Create build file
        run: |
          zip -r build.zip .

      - name: Upload package to S3
        run: aws s3 cp build.zip s3://owling-blog-bucket/

      - name: Create new EBS Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name owling-blog \
          --source-bundle S3Bucket="owling-blog-bucket",S3Key="build.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Update Application to latest version on EBS
        run: aws elasticbeanstalk update-environment --environment-name Owlingblog-env --version-label "ver-${{ github.sha }}"
