name: Deployer le blog
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > api/.env
          echo "${{ secrets.ENV_FILE_FRONT }}" > frontend/.env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push Docker Images to ECR for beanstalk
        run: |
          docker compose build

          docker tag production-backend-container public.ecr.aws/y9i0i5l9/blog-backend-container
          docker tag production-frontend-container public.ecr.aws/y9i0i5l9/blog-frontend-container
          docker tag web-server public.ecr.aws/y9i0i5l9/blog-nginx-container

          docker push public.ecr.aws/y9i0i5l9/blog-backend-container
          docker push public.ecr.aws/y9i0i5l9/blog-frontend-container
          docker push public.ecr.aws/y9i0i5l9/blog-nginx-container

      - name: Create build file
        run: |
          zip -r blog_build.zip .

      - name: Upload package to S3
        run: aws s3 cp blog_build.zip s3://owling-blog-bucket/

      - name: Create new EBS Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name owling-blog \
          --source-bundle S3Bucket="owling-blog-bucket", S3Key="blog_build.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Update Application to latest version on EBS
        run: aws elasticbeanstalk update-environment --environment-name Owlingblog-env --version-label "ver-${{ github.sha }}"
