name: Lint code
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version}}
        working-directory: ./api
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached venv
        working-directory: ./api
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Task
        working-directory: ./api
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

      - name: Install and upgrade pip and poetry
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip poetry

      - name: Install Dependencies
        working-directory: ./api
        run: |
          ./bin/task install

      - name: api lint
        working-directory: ./api
        run: |
          ./bin/task lint

      - name: frontend lint
        working-directory: ./frontend
        run: |
          npm ci
          npm run format
          npm run lint
 
